import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

import "./globals.css";
import { SessionManager } from "@/component/SessionManager";
import { ThemeManager } from "@/component/ThemeManager";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionManager>
          <ThemeManager>
            <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
          </ThemeManager>
        </SessionManager>
      </body>
    </html>
  );
}
